version: '3'
services: 
  my_sample_server:
    image: sample-server:2.0
    ports:
      - 8000:8000
  my_web_server:
    image: nginx:latest
    volumes: 
      - /d/Train/Node.js/practice/sample-server/web:/usr/share/nginx/html/nginx
    ports:
      - 8080:80